/* data.js - ゲーム内の静的データ定義 */

// ------------------------------------------------------------------
// 1. 施設データ (Buildings)
// ------------------------------------------------------------------
export const BUILDINGS = [
  // Tier 1
  {
    id: 'farm_lv1',
    name: '農場Lv1',
    description: '食糧生産を増加させる基本的な農業施設',
    level: 1,
    tier: 1,
    cost: { gold: 100 },
    buildTime: 30,
    effect: { type: 'foodProduction', value: 50 },
  },
  {
    id: 'mine_lv1',
    name: '鉱山Lv1',
    description: '鉱石を採掘する施設',
    level: 1,
    tier: 1,
    cost: { gold: 150 },
    buildTime: 45,
    effect: { type: 'oreProduction', value: 100 },
  },
  {
    id: 'workshop_lv1',
    name: '工房Lv1',
    description: '武器や装備を製造する施設',
    level: 1,
    tier: 1,
    cost: { gold: 200 },
    buildTime: 60,
    effect: { type: 'weaponProduction', value: 50 },
  },
  // Tier 2
  {
    id: 'farm_lv2',
    name: '農場Lv2',
    description: '大規模な農業施設',
    level: 2,
    tier: 2,
    cost: { gold: 500, ore: 20 },
    buildTime: 90,
    effect: { type: 'foodProduction', value: 100 },
    prerequisite: ['farm_lv1'],
  },
  {
    id: 'mine_lv2',
    name: '鉱山Lv2',
    description: '大規模な採掘施設',
    level: 2,
    tier: 2,
    cost: { gold: 600, ore: 30 },
    buildTime: 100,
    effect: { type: 'oreProduction', value: 200 },
    prerequisite: ['mine_lv1'],
  },
  {
    id: 'workshop_lv2',
    name: '工房Lv2',
    description: '大規模な製造施設',
    level: 2,
    tier: 2,
    cost: { gold: 700, ore: 25 },
    buildTime: 110,
    effect: { type: 'weaponProduction', value: 100 },
    prerequisite: ['workshop_lv1'],
  },
  {
    id: 'market',
    name: '市場',
    description: '交易と税収を強化する施設',
    level: 1,
    tier: 2,
    cost: { gold: 800 },
    buildTime: 120,
    effect: { type: 'tradeBonus', value: 20 },
    maxCount: 1,
  },
  {
    id: 'barracks',
    name: '兵舎',
    description: '兵士の訓練速度と士気を上昇させる',
    level: 1,
    tier: 2,
    cost: { gold: 1000 },
    buildTime: 150,
    effect: { type: 'trainingSpeed', value: 50 },
    maxCount: 1,
  },
  {
    id: 'training_ground',
    name: '訓練場',
    description: '士気を上昇させる施設',
    level: 1,
    tier: 2,
    cost: { gold: 600 },
    buildTime: 90,
    effect: { type: 'moraleBonus', value: 10 },
    maxCount: 1,
  },
  // Tier 3
  {
    id: 'farm_lv3',
    name: '農場Lv3',
    description: '最高効率の農業施設',
    level: 3,
    tier: 3,
    cost: { gold: 1500, ore: 50 },
    buildTime: 150,
    effect: { type: 'foodProduction', value: 150 },
    prerequisite: ['farm_lv2'],
  },
  {
    id: 'magic_tower_lv1',
    name: '魔法塔Lv1',
    description: '魔力を生成する施設',
    level: 1,
    tier: 3,
    cost: { gold: 3000, ore: 100 },
    buildTime: 180,
    effect: { type: 'manaGeneration', value: 10 },
    prerequisite: ['magic_theory'],
    maxCount: 1,
  },
  {
    id: 'research_lab',
    name: '研究所',
    description: '全技術の研究速度を上昇させる',
    level: 1,
    tier: 3,
    cost: { gold: 5000 },
    buildTime: 180,
    effect: { type: 'researchSpeed', value: 30 },
    maxCount: 1,
  },
  {
    id: 'walls_lv1',
    name: '城壁Lv1',
    description: '都市の防御力を強化する',
    level: 1,
    tier: 3,
    cost: { gold: 4000, ore: 200 },
    buildTime: 180,
    effect: { type: 'defense', value: 50 },
    maxCount: 1,
  },
];

// ------------------------------------------------------------------
// 2. 技術データ (Technologies)
// ------------------------------------------------------------------
export const TECHNOLOGIES = [
  // 農業ツリー
  {
    id: 'irrigation',
    name: '灌漑',
    description: '農場の効率を向上させる基本的な農業技術',
    tier: 1,
    category: 'agriculture',
    cost: { gold: 200 },
    researchTime: 60,
    effect: { type: 'farmEfficiency', value: 30 },
  },
  {
    id: 'crop_rotation',
    name: '輪作',
    description: '土地の生産性を高める農法',
    tier: 2,
    category: 'agriculture',
    cost: { gold: 500 },
    researchTime: 90,
    prerequisite: ['irrigation'],
    effect: { type: 'farmEfficiency', value: 50 },
  },
  {
    id: 'selective_breeding',
    name: '品種改良',
    description: '作物の品種を改良して収穫量を増加',
    tier: 3,
    category: 'agriculture',
    cost: { gold: 1200 },
    researchTime: 120,
    prerequisite: ['crop_rotation'],
    effect: { type: 'farmEfficiency', value: 100 },
  },
  // 軍事ツリー
  {
    id: 'archery',
    name: '弓術',
    description: '弓兵の戦闘力を向上させる',
    tier: 1,
    category: 'military',
    cost: { gold: 200 },
    researchTime: 60,
    effect: { type: 'archerPower', value: 30 },
  },
  {
    id: 'metallurgy',
    name: '冶金術',
    description: '武器と鎧の生産効率を向上',
    tier: 1,
    category: 'military',
    cost: { gold: 300 },
    researchTime: 90,
    effect: { type: 'weaponProduction', value: 20 },
  },
  {
    id: 'gunpowder',
    name: '火薬',
    description: '銃兵と大砲ユニットを解放、攻城戦闘力向上',
    tier: 2,
    category: 'military',
    cost: { gold: 800 },
    researchTime: 120,
    prerequisite: ['metallurgy'],
    effect: { type: 'siegePower', value: 30 },
  },
  // 経済ツリー
  {
    id: 'trade_network',
    name: '交易網',
    description: '税収と交易効率を向上',
    tier: 1,
    category: 'economy',
    cost: { gold: 600 },
    researchTime: 90,
    effect: { type: 'taxBonus', value: 10 },
  },
  {
    id: 'banking',
    name: '銀行',
    description: '税収を大幅に向上',
    tier: 2,
    category: 'economy',
    cost: { gold: 1200 },
    researchTime: 120,
    prerequisite: ['trade_network'],
    effect: { type: 'taxBonus', value: 20 },
  },
  // 魔法ツリー
  {
    id: 'magic_theory',
    name: '魔法理論',
    description: '魔法塔の建設を可能にする',
    tier: 1,
    category: 'magic',
    cost: { gold: 1000 },
    researchTime: 150,
    effect: { type: 'unlockBuilding', value: 1 },
  },
  {
    id: 'dimensional_magic',
    name: '次元魔法',
    description: '次元門建設を可能に（技術勝利ルート）',
    tier: 4,
    category: 'magic',
    cost: { gold: 10000, mana: 500 },
    researchTime: 180,
    prerequisite: ['magic_theory'], // 簡易化のため前提短縮
    effect: { type: 'unlockVictory', value: 1 },
  },
  // 工業ツリー
  {
    id: 'organization',
    name: '組織化',
    description: '同時建設2つを可能に',
    tier: 1,
    category: 'industry',
    cost: { gold: 500 },
    researchTime: 90,
    effect: { type: 'simultaneousConstruction', value: 2 },
  },
  {
    id: 'industrialization',
    name: '工業化',
    description: '同時建設3つを可能に、全生産+30%',
    tier: 2,
    category: 'industry',
    cost: { gold: 1500 },
    researchTime: 150,
    prerequisite: ['organization'],
    effect: { type: 'productionBonus', value: 30 },
  }
];

// ------------------------------------------------------------------
// 3. AI国家データ (Nations)
// ------------------------------------------------------------------
export const NATION_TEMPLATES = [
  // 序盤向け（弱い敵）
  {
    name: '山賊団',
    personality: 'aggressive',
    description: '小規模な盗賊集団',
    initialPopulation: 30,
    initialMilitaryPower: 15,
    aggressiveness: 70,
    expansionDesire: 50,
  },
  {
    name: '辺境の村',
    personality: 'cautious',
    description: '小さな自治村落',
    initialPopulation: 50,
    initialMilitaryPower: 20,
    aggressiveness: 10,
    expansionDesire: 20,
  },
  // 中盤向け
  {
    name: '商人連合',
    personality: 'commercial',
    description: '交易を重視する商業国家',
    initialPopulation: 200,
    initialMilitaryPower: 80,
    aggressiveness: 15,
    expansionDesire: 40,
  },
  {
    name: '蛮族連合',
    personality: 'aggressive',
    description: '略奪を生業とする荒くれ者の集団',
    initialPopulation: 300,
    initialMilitaryPower: 150,
    aggressiveness: 90,
    expansionDesire: 80,
  },
  // 終盤向け（強い敵）
  {
    name: '聖守護王国',
    personality: 'cautious',
    description: '防衛を重視する慎重な王国',
    initialPopulation: 600,
    initialMilitaryPower: 300,
    aggressiveness: 20,
    expansionDesire: 30,
  },
  {
    name: '鉄血帝国',
    personality: 'aggressive',
    description: '軍事力を重視する好戦的な帝国',
    initialPopulation: 800,
    initialMilitaryPower: 400,
    aggressiveness: 85,
    expansionDesire: 90,
  },
  {
    name: '学術都市',
    personality: 'scientific',
    description: '技術開発を最優先する未来国家',
    initialPopulation: 400,
    initialMilitaryPower: 200,
    aggressiveness: 25,
    expansionDesire: 35,
  },
];

// ------------------------------------------------------------------
// 4. 英雄・スペシャリストデータ (Heroes)
// ------------------------------------------------------------------
export const HERO_TEMPLATES = [
  {
    name: '剣聖アリエス',
    combatPower: 100,
    specialAbility: {
      name: '無双',
      description: '戦闘開始時に敵50人を即死させる',
      effect: { type: 'instantKill', value: 50, trigger: 'battleStart' },
    },
    salary: 500,
  },
  {
    name: '大魔導師ゼノ',
    combatPower: 30,
    specialAbility: {
      name: '大結界',
      description: '都市防御+50%',
      effect: { type: 'defenseBonus', value: 50, trigger: 'passive' },
    },
    salary: 300,
    manaCost: 10,
  },
  {
    name: '疾風のリン',
    combatPower: 80,
    specialAbility: {
      name: '奇襲',
      description: '先制攻撃で追加ダメージ',
      effect: { type: 'firstStrike', value: 30, trigger: 'battleStart' },
    },
    salary: 450,
  },
];

export const SPECIALIST_TEMPLATES = [
  {
    name: '鍛冶師ゴロン',
    type: 'blacksmith',
    bonus: { type: 'weaponProduction', value: 10 },
    salary: 50,
  },
  {
    name: '商人ミレイユ',
    type: 'merchant',
    bonus: { type: 'tradeBonus', value: 5 },
    salary: 30,
  },
  {
    name: '農場長オルガ',
    type: 'farmer',
    bonus: { type: 'foodProduction', value: 15 },
    salary: 40,
  },
];